name: Trinethra OS Compilation Engine

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blueprint
        uses: actions/checkout@v3
        with:
          repository: noushik1712-OS/Trinethra-OS-Blueprint
          token: ${{ secrets.GH_PAT_TOKEN }}
          path: royalos_source

      - name: Setup Crave
        run: |
          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
          sudo mv crave /usr/local/bin/

      - name: Run Build
        run: |
          crave config set --token ${{ secrets.CRAVE_TOKEN }}
          # Register the project explicitly
          crave project init https://github.com/noushik1712-OS/Project-Trinethra-Build
          # Run the build
          crave run --no-patch -- "cd royalos_source && source build/envsetup.sh && lunch royal_trinethra-userdebug && mka bacon"
