name: Trinethra OS Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Crave
        run: |
          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
          sudo mv crave /usr/local/bin/
      
      - name: Build OS
        env:
          CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}
        run: |
          # Set the token
          crave config set --token $CRAVE_TOKEN
          # Explicitly initialize the project using the URL
          crave project init https://github.com/noushik1712-OS/Project-Trinethra-Build
          # Execute the build directly
          crave run -- "source build/envsetup.sh && lunch aosp_arm64-userdebug && mka bacon"
